# Generated by Django 5.0.7 on 2024-07-17 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bouquet_makers_needed', models.IntegerField()),
                ('drivers_needed', models.IntegerField()),
                ('group', models.IntegerField()),
                ('closed', models.BooleanField(default=False)),
                ('bouquet_makers', models.ManyToManyField(blank=True, related_name='bouquet_makers', to=settings.AUTH_USER_MODEL)),
                ('drivers', models.ManyToManyField(blank=True, related_name='drivers', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, related_name='recipients', to='recipient.recipient')),
            ],
        ),
    ]
