# Generated by Django 5.0.7 on 2024-07-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
