# Generated by Django 5.0.7 on 2024-07-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0003_alter_recipient_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='phone',
        ),
    ]
