# Generated by Django 5.0.7 on 2024-07-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0002_recipient_email_recipient_phone'),
        ('recipient', '0004_remove_recipient_email_remove_recipient_phone'),
    ]

    operations = [
    ]
