# Generated by Django 5.0.7 on 2024-07-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0005_merge_20240726_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='phone',
        ),
    ]
